title: DrugBot
favicon: favicon.ico
logo: assets/images/drugbot.png
masthead: assets/images/drugbot.png
# masthead: favicon.png 
email: maayanlabapps@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  DrugBot is a Slack application developed by the Ma'ayan Laboratory of Computational Systems Biology
baseurl: "/DrugBot/" # the subpath of your site, e.g. /blog
url: "https://maayanlab.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: MaayanLab
github_username:  MaayanLab

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
